"""Tabela Usuarios

Revision ID: 30f1f4d4def9
Revises:
Create Date: 2024-11-22 10:28:21.427908
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30f1f4d4def9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Usuarios',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('sobrenome', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('nome_usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=200), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('nome_usuario'),
        schema='management',
    )
    op.create_table(
        'Usuarios_version',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'nome', sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            'sobrenome',
            sa.String(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'cpf', sa.String(length=14), autoincrement=False, nullable=True
        ),
        sa.Column(
            'email', sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            'nome_usuario',
            sa.String(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'senha', sa.String(length=200), autoincrement=False, nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            'transaction_id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'transaction_id'),
        schema='management',
    )
    with op.batch_alter_table(
        'Usuarios_version', schema='management'
    ) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_management_Usuarios_version_end_transaction_id'),
            ['end_transaction_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_management_Usuarios_version_operation_type'),
            ['operation_type'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_management_Usuarios_version_transaction_id'),
            ['transaction_id'],
            unique=False,
        )

    op.create_table(
        'transaction',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('remote_addr', sa.String(length=50), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('issued_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['management.Usuarios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))

    op.drop_table('transaction')
    with op.batch_alter_table(
        'Usuarios_version', schema='management'
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_management_Usuarios_version_transaction_id')
        )
        batch_op.drop_index(
            batch_op.f('ix_management_Usuarios_version_operation_type')
        )
        batch_op.drop_index(
            batch_op.f('ix_management_Usuarios_version_end_transaction_id')
        )

    op.drop_table('Usuarios_version', schema='management')
    op.drop_table('Usuarios', schema='management')
    # ### end Alembic commands ###
