"""Tabela de Funções

Revision ID: 364b4dd4eaf8
Revises: 4adef8697756
Create Date: 2024-11-22 21:24:47.824413
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364b4dd4eaf8'
down_revision = '4adef8697756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Funcoes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('funcao', sa.String(length=20), nullable=True),
        sa.Column('nivel', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='management',
    )
    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Enderecos_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Enderecos_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Telefones_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Telefones_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Telefones_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Telefones_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Enderecos_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Enderecos_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )

    op.drop_table('Funcoes', schema='management')
    # ### end Alembic commands ###
