"""empty message

Revision ID: 602af34775d4
Revises: f3b1e2ffd7f7
Create Date: 2024-11-22 16:57:56.935842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602af34775d4'
down_revision = 'f3b1e2ffd7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=19), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id'),
    schema='management'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Empresas', schema='management')
    # ### end Alembic commands ###
