"""mudança de usuario para cliente

Revision ID: 80848953a275
Revises: a037ccbe64ab
Create Date: 2024-11-29 11:22:23.295108
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80848953a275'
down_revision = 'a037ccbe64ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Clientes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('sobrenome', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('nome_usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=200), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('nome_usuario'),
        schema='management',
    )
    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(
            'Enderecos_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Enderecos_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Clientes',
            ['cliente_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcao_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcionario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Funcoes',
            ['funcao_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(
            'Telefones_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Telefones_funcionario_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Telefones_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Clientes',
            ['cliente_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.drop_column('usuario_id')

    op.drop_table('Usuarios', schema='management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'usuario_id', sa.UUID(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Telefones_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Telefones_funcionario_id_fkey',
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Telefones_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcionario_id_fkey',
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcao_id_fkey',
            'Funcoes',
            ['funcao_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'usuario_id', sa.UUID(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Enderecos_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Enderecos_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('cliente_id')

    op.create_table(
        'Usuarios',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            'sobrenome',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False
        ),
        sa.Column(
            'email',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'nome_usuario',
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'senha', sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            'data_criacao',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'data_atualizacao',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='Usuarios_pkey'),
        sa.UniqueConstraint('email', name='Usuarios_email_key'),
        sa.UniqueConstraint('id', name='Usuarios_id_key'),
        sa.UniqueConstraint('nome_usuario', name='Usuarios_nome_usuario_key'),
    )
    op.drop_table('Clientes', schema='management')
    # ### end Alembic commands ###
