"""Commit inicial

Revision ID: 925461498a71
Revises:
Create Date: 2024-11-22 20:00:57.680568
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925461498a71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Empresas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=True),
        sa.Column('razao_social', sa.String(length=100), nullable=False),
        sa.Column('cnpj', sa.String(length=19), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cnpj'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'TokenBlockList',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('TokenBlockList', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_TokenBlockList_jti'), ['jti'], unique=False
        )

    op.create_table(
        'Usuarios',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('sobrenome', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('nome_usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=200), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('nome_usuario'),
    )
    op.create_table(
        'Funcionarios',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('sobrenome', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('nome_usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=200), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('empresa_id', sa.UUID(), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['empresa_id'],
            ['Empresas.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('nome_usuario'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Funcionarios')
    op.drop_table('Usuarios')
    with op.batch_alter_table('TokenBlockList', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TokenBlockList_jti'))

    op.drop_table('TokenBlockList')
    op.drop_table('Empresas')
    # ### end Alembic commands ###
