"""Ajuste no tamanho do campo

Revision ID: aa0d3f724221
Revises: d5abda7fb5bc
Create Date: 2024-11-25 10:13:20.413965
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0d3f724221'
down_revision = 'd5abda7fb5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresas', schema=None) as batch_op:
        batch_op.alter_column(
            'cnpj',
            existing_type=sa.VARCHAR(length=19),
            type_=sa.String(length=18),
            existing_nullable=False,
        )

    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Enderecos_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Enderecos_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcao_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcionario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Funcoes',
            ['funcao_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Telefones_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Telefones_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Telefones_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Telefones_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcionario_id_fkey',
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcao_id_fkey',
            'Funcoes',
            ['funcao_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Enderecos_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Enderecos_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Empresas', schema=None) as batch_op:
        batch_op.alter_column(
            'cnpj',
            existing_type=sa.String(length=18),
            type_=sa.VARCHAR(length=19),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
