"""Tabela de Endereços

Revision ID: b49ecba3e42d
Revises: f6446679c6d4
Create Date: 2024-11-22 21:05:31.570004
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49ecba3e42d'
down_revision = 'f6446679c6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Enderecos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('logradouro', sa.String(length=200), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('bairro', sa.String(length=50), nullable=False),
        sa.Column('cidade', sa.String(length=50), nullable=False),
        sa.Column('estado', sa.String(length=2), nullable=False),
        sa.Column('cep', sa.String(length=9), nullable=False),
        sa.Column('complemento', sa.String(length=100), nullable=True),
        sa.Column('principal', sa.Boolean(), nullable=True),
        sa.Column('empresa_id', sa.UUID(), nullable=True),
        sa.Column('usuario_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['empresa_id'], ['management.Empresas.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['usuario_id'], ['management.Usuarios.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='management',
    )
    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    op.drop_table('Enderecos', schema='management')
    # ### end Alembic commands ###
