"""Campo fk funcionario na tabela telefones

Revision ID: dd17d0ced380
Revises: 91ea5a72e47f
Create Date: 2024-11-26 22:17:23.679609
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd17d0ced380'
down_revision = '91ea5a72e47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Enderecos_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Enderecos_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcao_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'FuncaoFuncionario_funcionario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Funcoes',
            ['funcao_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('funcionario_id', sa.UUID(), nullable=True)
        )
        batch_op.drop_constraint(
            'Telefones_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'Telefones_usuario_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Usuarios',
            ['usuario_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Telefones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Telefones_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Telefones_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('funcionario_id')

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('FuncaoFuncionario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcionario_id_fkey',
            'Funcionarios',
            ['funcionario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'FuncaoFuncionario_funcao_id_fkey',
            'Funcoes',
            ['funcao_id'],
            ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('Enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Enderecos_usuario_id_fkey',
            'Usuarios',
            ['usuario_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'Enderecos_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###
