"""Tabelas Usuarios e Token

Revision ID: ee1f717c66dc
Revises:
Create Date: 2024-11-22 13:08:12.423073
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ee1f717c66dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Usuarios',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('sobrenome', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('nome_usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=200), nullable=True),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'data_atualizacao', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('nome_usuario'),
        schema='management',
    )
    op.create_table(
        'Usuarios_version',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'nome', sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            'sobrenome',
            sa.String(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'cpf', sa.String(length=14), autoincrement=False, nullable=True
        ),
        sa.Column(
            'email', sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            'nome_usuario',
            sa.String(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'senha', sa.String(length=200), autoincrement=False, nullable=True
        ),
        sa.Column('ativo', sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            'transaction_id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'transaction_id'),
        schema='management',
    )
    op.create_index(
        op.f('ix_management_Usuarios_version_end_transaction_id'),
        'Usuarios_version',
        ['end_transaction_id'],
        unique=False,
        schema='management',
    )
    op.create_index(
        op.f('ix_management_Usuarios_version_operation_type'),
        'Usuarios_version',
        ['operation_type'],
        unique=False,
        schema='management',
    )
    op.create_index(
        op.f('ix_management_Usuarios_version_transaction_id'),
        'Usuarios_version',
        ['transaction_id'],
        unique=False,
        schema='management',
    )
    op.create_table(
        'token_block_list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='management',
    )
    op.create_index(
        op.f('ix_management_token_block_list_jti'),
        'token_block_list',
        ['jti'],
        unique=False,
        schema='management',
    )
    op.create_table(
        'transaction',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('remote_addr', sa.String(length=50), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('issued_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['management.Usuarios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_transaction_user_id'),
        'transaction',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(
        op.f('ix_management_token_block_list_jti'),
        table_name='token_block_list',
        schema='management',
    )
    op.drop_table('token_block_list', schema='management')
    op.drop_index(
        op.f('ix_management_Usuarios_version_transaction_id'),
        table_name='Usuarios_version',
        schema='management',
    )
    op.drop_index(
        op.f('ix_management_Usuarios_version_operation_type'),
        table_name='Usuarios_version',
        schema='management',
    )
    op.drop_index(
        op.f('ix_management_Usuarios_version_end_transaction_id'),
        table_name='Usuarios_version',
        schema='management',
    )
    op.drop_table('Usuarios_version', schema='management')
    op.drop_table('Usuarios', schema='management')
    # ### end Alembic commands ###
