"""Alterando nome da tabela TokenBlockList

Revision ID: f3b1e2ffd7f7
Revises: ee1f717c66dc
Create Date: 2024-11-22 13:09:19.297152
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3b1e2ffd7f7'
down_revision = 'ee1f717c66dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'TokenBlockList',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='management',
    )
    op.create_index(
        op.f('ix_management_TokenBlockList_jti'),
        'TokenBlockList',
        ['jti'],
        unique=False,
        schema='management',
    )
    op.drop_index(
        'ix_management_token_block_list_jti',
        table_name='token_block_list',
        schema='management',
    )
    op.drop_table('token_block_list', schema='management')
    op.create_unique_constraint(None, 'Usuarios', ['id'], schema='management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuarios', schema='management', type_='unique')
    op.create_table(
        'token_block_list',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            'data_criacao',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name='token_block_list_pkey'),
        schema='management',
    )
    op.create_index(
        'ix_management_token_block_list_jti',
        'token_block_list',
        ['jti'],
        unique=False,
        schema='management',
    )
    op.drop_index(
        op.f('ix_management_TokenBlockList_jti'),
        table_name='TokenBlockList',
        schema='management',
    )
    op.drop_table('TokenBlockList', schema='management')
    # ### end Alembic commands ###
