"""Tabela de Endereços

Revision ID: f6446679c6d4
Revises: 6fb4247f8d0d
Create Date: 2024-11-22 21:02:45.593370
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6446679c6d4'
down_revision = '6fb4247f8d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(
            'Funcionarios_empresa_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'Empresas',
            ['empresa_id'],
            ['id'],
            referent_schema='management',
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'Funcionarios_empresa_id_fkey',
            'Empresas',
            ['empresa_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###
